/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.19
 * Generated at: 2012-12-15 13:19:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    ul.rightTools {float:right; display:block;}\r\n");
      out.write("    ul.rightTools li{float:left; display:block; margin-left:5px}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pageContent\" style=\"padding:5px\">\r\n");
      out.write("    <div class=\"tabs\">\r\n");
      out.write("        <div class=\"tabsHeader\">\r\n");
      out.write("            <div class=\"tabsHeaderContent\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>实验室检测</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>病人处方</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>病人服药情况</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>基线调查</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>随访</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tabsContent\">\r\n");
      out.write("            <div>\r\n");
      out.write("    \r\n");
      out.write("                <div layoutH=\"146\" style=\"float:left; display:block; overflow:auto; width:240px; border:solid 1px #CCC; line-height:21px; background:#fff\">\r\n");
      out.write("                    <ul class=\"tree treeFolder\">\r\n");
      out.write("                        <li><a href=\"javascript\">实验室检测</a>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"demo/pagination/list1.html\" target=\"ajax\" rel=\"jbsxBox\">尿检</a></li>\r\n");
      out.write("                                <li><a href=\"demo/pagination/list1.html\" target=\"ajax\" rel=\"jbsxBox\">HIV检测</a></li>\r\n");
      out.write("                                <li><a href=\"demo/pagination/list1.html\" target=\"ajax\" rel=\"jbsxBox\">HCV检测</a></li>\r\n");
      out.write("                                <li><a href=\"demo/pagination/list1.html\" target=\"ajax\" rel=\"jbsxBox\">TB检测</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                     </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"jbsxBox\" class=\"unitBox\" style=\"margin-left:246px;\">\r\n");
      out.write("                    <!--#include virtual=\"list1.html\" -->\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div>病人处方</div>\r\n");
      out.write("            \r\n");
      out.write("            <div>病人服药情况</div>\r\n");
      out.write("            \r\n");
      out.write("            <div>基线调查</div>\r\n");
      out.write("            \r\n");
      out.write("            <div>随访</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tabsFooter\">\r\n");
      out.write("            <div class=\"tabsFooterContent\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
