/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.19
 * Generated at: 2013-02-03 07:49:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pub.util.config.Config;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\r\n");
      out.write("<title>");
      out.print(Config.params.getString("sys.company", "Ahpo") );
      out.write("管理平台</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"dwz/themes/default/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("<link href=\"dwz/themes/css/core.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("<link href=\"dwz/themes/css/print.css\" rel=\"stylesheet\" type=\"text/css\" media=\"print\"/>\r\n");
      out.write("<link href=\"dwz/uploadify/css/uploadify.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("<!--[if IE]>\r\n");
      out.write("<link href=\"themes/css/ieHack.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<script src=\"dwz/js/speedup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/jquery-1.7.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/jquery.cookie.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/jquery.validate.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/jquery.bgiframe.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/xheditor/xheditor-1.1.14-zh-cn.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/uploadify/scripts/swfobject.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/uploadify/scripts/jquery.uploadify.v2.1.0.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- svg图表  supports Firefox 3.0+, Safari 3.0+, Chrome 5.0+, Opera 9.5+ and Internet Explorer 6.0+ -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"dwz/chart/raphael.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"dwz/chart/g.raphael.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"dwz/chart/g.bar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"dwz/chart/g.line.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"dwz/chart/g.pie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"dwz/chart/g.dot.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"dwz/js/dwz.core.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.util.date.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.validate.method.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.regional.zh.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.barDrag.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.drag.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.tree.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.accordion.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.ui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.theme.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.switchEnv.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.alertMsg.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.contextmenu.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.navTab.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.tab.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.resize.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.dialog.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.dialogDrag.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.sortDrag.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.cssTable.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.stable.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.taskBar.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.ajax.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.pagination.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.database.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.datepicker.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.effects.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.panel.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.checkbox.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.history.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.combox.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"dwz/js/dwz.print.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--\r\n");
      out.write("<script src=\"bin/dwz.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<script src=\"dwz/js/dwz.regional.zh.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("    DWZ.init(\"dwz/dwz.frag.xml\", {\r\n");
      out.write("        loginUrl:\"login_dialog.html\", loginTitle:\"登录\",  // 弹出登录对话框\r\n");
      out.write("//      loginUrl:\"login.html\",  // 跳到登录页面\r\n");
      out.write("        statusCode:{ok:200, error:300, timeout:301}, //【可选】\r\n");
      out.write("        pageInfo:{pageNum:\"pageNum\", numPerPage:\"numPerPage\", orderField:\"orderField\", orderDirection:\"orderDirection\"}, //【可选】\r\n");
      out.write("        debug:false,    // 调试模式 【true|false】\r\n");
      out.write("        callback:function(){\r\n");
      out.write("            initEnv();\r\n");
      out.write("            $(\"#themeList\").theme({themeBase:\"themes\"}); // themeBase 相对于index页面的主题base路径\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body scroll=\"no\">\r\n");
      out.write("    <div id=\"layout\">\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div class=\"headerNav\">\r\n");
      out.write("                <a class=\"logo\" href=\"dwz/index.html\" target=\"_blank\">标志</a>\r\n");
      out.write("                <ul class=\"nav\">\r\n");
      out.write("                    <li id=\"switchEnvBox\"><a href=\"javascript:\">（<span>杭州</span>）切换城市</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"sidebar_1.html\">北京</a></li>\r\n");
      out.write("                            <li><a href=\"sidebar_2.html\">上海</a></li>\r\n");
      out.write("                            <li><a href=\"sidebar_2.html\">南京</a></li>\r\n");
      out.write("                            <li><a href=\"sidebar_2.html\">深圳</a></li>\r\n");
      out.write("                            <li><a href=\"sidebar_2.html\">广州</a></li>\r\n");
      out.write("                            <li><a href=\"sidebar_2.html\">天津</a></li>\r\n");
      out.write("                            <li><a href=\"sidebar_2.html\">杭州</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"admin/about.html\" target=\"dialog\" width=\"600\">关于</a></li>\r\n");
      out.write("                    <li><a href=\"admin/changepwd.html\" target=\"dialog\" width=\"600\">设置</a></li>\r\n");
      out.write("                    <li><a href=\"logout.action\">退出</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul class=\"themeList\" id=\"themeList\">\r\n");
      out.write("                \t<li><marquee>fsdfsdfffffffffffffffddffffffffffffffffffffffffffffffffffffffffffffff</marquee></li>\r\n");
      out.write("                \t<li></li>\r\n");
      out.write("                    <li theme=\"default\"><div class=\"selected\">蓝色</div></li>\r\n");
      out.write("                    <li theme=\"green\"><div>绿色</div></li>\r\n");
      out.write("                    <!--<li theme=\"red\"><div>红色</div></li>-->\r\n");
      out.write("                    <li theme=\"purple\"><div>紫色</div></li>\r\n");
      out.write("                    <li theme=\"silver\"><div>银色</div></li>\r\n");
      out.write("                    <li theme=\"azure\"><div>天蓝</div></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- navMenu -->\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"leftside\">\r\n");
      out.write("            <div id=\"sidebar_s\">\r\n");
      out.write("                <div class=\"collapse\">\r\n");
      out.write("                    <div class=\"toggleCollapse\"><div></div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"sidebar\">\r\n");
      out.write("                <div class=\"toggleCollapse\"><h2>主菜单</h2><div>收缩</div></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"accordion\" fillSpace=\"sidebar\">\r\n");
      out.write("                    ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"accordionHeader\">\r\n");
      out.write("                        <h2><span>Folder</span>界面组件</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"accordionContent\">\r\n");
      out.write("                        <ul class=\"tree treeFolder\">\r\n");
      out.write("                            <li><a href=\"tabsPage.html\" target=\"navTab\">主框架面板</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"main.html\" target=\"navTab\" rel=\"main\">我的主页</a></li>\r\n");
      out.write("                                    <li><a href=\"http://www.baidu.com\" target=\"navTab\" rel=\"page1\">页面一(外部页面)</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_page2.html\" target=\"navTab\" rel=\"external\" external=\"true\">iframe navTab页面</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_page1.html\" target=\"navTab\" rel=\"page1\" fresh=\"false\">替换页面一</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_page2.html\" target=\"navTab\" rel=\"page2\">页面二</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_page4.html\" target=\"navTab\" rel=\"page3\" title=\"页面三（自定义标签名）\">页面三</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_page4.html\" target=\"navTab\" rel=\"page4\" fresh=\"false\">测试页面（fresh=\"false\"）</a></li>\r\n");
      out.write("                                    <li><a href=\"w_editor.html\" target=\"navTab\">表单提交会话超时</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/common/ajaxTimeout.html\" target=\"navTab\">navTab会话超时</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/common/ajaxTimeout.html\" target=\"dialog\">dialog会话超时</a></li>\r\n");
      out.write("                                    <li><a href=\"index_menu.html\" target=\"_blank\">横向导航条</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                            <li><a>常用组件</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"w_panel.html\" target=\"navTab\" rel=\"w_panel\">面板</a></li>\r\n");
      out.write("                                    <li><a href=\"w_tabs.html\" target=\"navTab\" rel=\"w_tabs\">选项卡面板</a></li>\r\n");
      out.write("                                    <li><a href=\"w_dialog.html\" target=\"navTab\" rel=\"w_dialog\">弹出窗口</a></li>\r\n");
      out.write("                                    <li><a href=\"w_alert.html\" target=\"navTab\" rel=\"w_alert\">提示窗口</a></li>\r\n");
      out.write("                                    <li><a href=\"w_list.html\" target=\"navTab\" rel=\"w_list\">CSS表格容器</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_page1.html\" target=\"navTab\" rel=\"w_table\">表格容器</a></li>\r\n");
      out.write("                                    <li><a href=\"w_removeSelected.html\" target=\"navTab\" rel=\"w_table\">表格数据库排序+批量删除</a></li>\r\n");
      out.write("                                    <li><a href=\"w_tree.html\" target=\"navTab\" rel=\"w_tree\">树形菜单</a></li>\r\n");
      out.write("                                    <li><a href=\"w_accordion.html\" target=\"navTab\" rel=\"w_accordion\">滑动菜单</a></li>\r\n");
      out.write("                                    <li><a href=\"w_editor.html\" target=\"navTab\" rel=\"w_editor\">编辑器</a></li>\r\n");
      out.write("                                    <li><a href=\"w_datepicker.html\" target=\"navTab\" rel=\"w_datepicker\">日期控件</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/database/db_widget.html\" target=\"navTab\" rel=\"db\">suggest+lookup+主从结构</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/database/treeBringBack.html\" target=\"navTab\" rel=\"db\">tree查找带回</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/sortDrag/1.html\" target=\"navTab\" rel=\"sortDrag\">单个sortDrag示例</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/sortDrag/2.html\" target=\"navTab\" rel=\"sortDrag\">多个sortDrag示例</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                                    \r\n");
      out.write("                            <li><a>表单组件</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"w_validation.html\" target=\"navTab\" rel=\"w_validation\">表单验证</a></li>\r\n");
      out.write("                                    <li><a href=\"w_button.html\" target=\"navTab\" rel=\"w_button\">按钮</a></li>\r\n");
      out.write("                                    <li><a href=\"w_textInput.html\" target=\"navTab\" rel=\"w_textInput\">文本框/文本域</a></li>\r\n");
      out.write("                                    <li><a href=\"w_combox.html\" target=\"navTab\" rel=\"w_combox\">下拉菜单</a></li>\r\n");
      out.write("                                    <li><a href=\"w_checkbox.html\" target=\"navTab\" rel=\"w_checkbox\">多选框/单选框</a></li>\r\n");
      out.write("                                    <li><a href=\"demo_upload.html\" target=\"navTab\" rel=\"demo_upload\">iframeCallback表单提交</a></li>\r\n");
      out.write("                                    <li><a href=\"w_uploadify.html\" target=\"navTab\" rel=\"w_uploadify\">uploadify多文件上传</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a>组合应用</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"demo/pagination/layout1.html\" target=\"navTab\" rel=\"pagination1\">局部刷新分页1</a></li>\r\n");
      out.write("                                    <li><a href=\"demo/pagination/layout2.html\" target=\"navTab\" rel=\"pagination2\">局部刷新分页2</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a>图表</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"chart/test/barchart.html\" target=\"navTab\" rel=\"chart\">柱状图(垂直)</a></li>\r\n");
      out.write("                                    <li><a href=\"chart/test/hbarchart.html\" target=\"navTab\" rel=\"chart\">柱状图(水平)</a></li>\r\n");
      out.write("                                    <li><a href=\"chart/test/linechart.html\" target=\"navTab\" rel=\"chart\">折线图</a></li>\r\n");
      out.write("                                    <li><a href=\"chart/test/piechart.html\" target=\"navTab\" rel=\"chart\">饼图</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"dwz.frag.xml\" target=\"navTab\" external=\"true\">dwz.frag.xml</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("            <div id=\"navTab\" class=\"tabsPage\">\r\n");
      out.write("                <div class=\"tabsPageHeader\">\r\n");
      out.write("                    <div class=\"tabsPageHeaderContent\"><!-- 显示左右控制时添加 class=\"tabsPageHeaderMargin\" -->\r\n");
      out.write("                        <ul class=\"navTab-tab\">\r\n");
      out.write("                            <li tabid=\"main\" class=\"main\"><a href=\"javascript:;\"><span><span class=\"home_icon\">我的主页</span></span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tabsLeft\">left</div><!-- 禁用只需要添加一个样式 class=\"tabsLeft tabsLeftDisabled\" -->\r\n");
      out.write("                    <div class=\"tabsRight\">right</div><!-- 禁用只需要添加一个样式 class=\"tabsRight tabsRightDisabled\" -->\r\n");
      out.write("                    <div class=\"tabsMore\">more</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"tabsMoreList\">\r\n");
      out.write("                    <li><a href=\"javascript:;\">我的主页</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"navTab-panel tabsPageContent layoutBox\">\r\n");
      out.write("                    <div class=\"page unitBox\">\r\n");
      out.write("                        <div class=\"accountInfo\">\r\n");
      out.write("                            <div class=\"alertInfo\">\r\n");
      out.write("                                <h2><a href=\"#\">使用手册(PDF)</a></h2>\r\n");
      out.write("                                <a href=\"#\">演示视频(SWF)</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p><span>");
      out.print(Config.params.getString("sys.company", "Ahpo") );
      out.write("管理平台</span></p>\r\n");
      out.write("                            <p>Done is better than perfect.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pageFormContent\" layoutH=\"80\" style=\"margin-right:230px\">\r\n");
      out.write("                            \r\n");
      out.write("                            <p style=\"color:red\">Over thinking ruins you.</p>\r\n");
      out.write("                            <p style=\"color:red\">Stay hungry, stay foolish.</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"divider\"></div>\r\n");
      out.write("<h2>在细节上展现魅力，不仅仅是在正常情况下，也要在不正常情况下……</h2>\r\n");
      out.write("<div class=\"divider\"></div>\r\n");
      out.write("<p>1.每天读书</p><p>2.学习新的语言</p>\r\n");
      out.write("<p>3.打造你的灵感空间</p><p>4.战胜你的恐惧</p>\r\n");
      out.write("<p>5.升级技能</p><p>6.给未来的自己写一封信</p>\r\n");
      out.write("<p>7.承认自己的缺点</p><p>8.立即行动</p>\r\n");
      out.write("<p>9.向你佩服的人学习</p><p>10.减少在QQ上的时间</p>\r\n");
      out.write("<p>11.培养一个新的习惯</p><p>12.让过去的过去</p>\r\n");
      out.write("<p>13.帮助他人</p><p>14.好好休息。</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"divider\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div style=\"width:230px;position: absolute;top:60px;right:0\" layoutH=\"80\">\r\n");
      out.write("                        \t<!-- \r\n");
      out.write("                            <iframe width=\"100%\" height=\"430\" class=\"share_self\"  frameborder=\"0\" scrolling=\"no\" src=\"http://widget.weibo.com/weiboshow/index.php?width=0&height=430&fansRow=2&ptype=1&skin=1&isTitle=0&noborder=1&isWeibo=1&isFans=0&uid=1739071261&verifier=c683dfe7\"></iframe>\r\n");
      out.write("                            -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"footer\"> Copyright &copy; 2012 ");
      out.print(Config.params.getString("sys.company", "Ahpo") );
      out.write(" Inc. All Rights Reserved.</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent(null);
    // /main.jsp(142,20) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("#session.USER_MENU!=null");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("                        ");
        if (_jspx_meth_s_005fiterator_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        \r\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f0 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.get(org.apache.struts2.views.jsp.IteratorTag.class);
    _jspx_th_s_005fiterator_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fiterator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
    // /main.jsp(143,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f0.setValue("#session.USER_MENU");
    // /main.jsp(143,24) name = status type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f0.setStatus("rowstatus");
    // /main.jsp(143,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f0.setVar("t");
    int _jspx_eval_s_005fiterator_005f0 = _jspx_th_s_005fiterator_005f0.doStartTag();
    if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fiterator_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fiterator_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("                            <div class=\"accordionHeader\">\r\n");
        out.write("                                <h2><span>Folder</span>");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("</h2>\r\n");
        out.write("                            </div>\r\n");
        out.write("                            <ul class=\"tree treeFolder\">\r\n");
        out.write("                                ");
        if (_jspx_meth_s_005fiterator_005f1(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                            </ul>\r\n");
        out.write("                        ");
        int evalDoAfterBody = _jspx_th_s_005fiterator_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fiterator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.reuse(_jspx_th_s_005fiterator_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.reuse(_jspx_th_s_005fiterator_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /main.jsp(145,55) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("sysResFuncRelation.sysResource.resName");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f1 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.get(org.apache.struts2.views.jsp.IteratorTag.class);
    _jspx_th_s_005fiterator_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fiterator_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /main.jsp(148,32) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f1.setValue("child");
    // /main.jsp(148,32) name = status type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f1.setStatus("rowstatus");
    // /main.jsp(148,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f1.setVar("tt");
    int _jspx_eval_s_005fiterator_005f1 = _jspx_th_s_005fiterator_005f1.doStartTag();
    if (_jspx_eval_s_005fiterator_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fiterator_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fiterator_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fiterator_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("                                    <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysResFuncRelation.sysResource.url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" target=\"navTab\" rel=\"page");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysResFuncRelation.sysResource.resName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysResFuncRelation.sysResource.resName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</a></li>\r\n");
        out.write("                                ");
        int evalDoAfterBody = _jspx_th_s_005fiterator_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fiterator_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fiterator_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.reuse(_jspx_th_s_005fiterator_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvar_005fvalue_005fstatus.reuse(_jspx_th_s_005fiterator_005f1);
    return false;
  }
}
